// Communes data (extracted from the provided list)
const communes = [
const communes = [
    { name: "VILLENEUVE SOUS CHARIGNY", insee: 21696, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLERS LA FAYE", insee: 21698, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VILLERS LES POTS", insee: 21699, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "VILLERS PATRAS", insee: 21700, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLERS ROTIN", insee: 21701, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "VILLEY SUR TILLE", insee: 21702, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VILLIERS EN MORVAN", insee: 21703, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VILLIERS LE DUC", insee: 21704, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLOTTE ST SEINE", insee: 21705, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VILLOTTE SUR OURCE", insee: 21706, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLY EN AUXOIS", insee: 21707, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLY LE MOUTIER", insee: 21708, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VISERNY", insee: 21709, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VITTEAUX", insee: 21710, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VIX", insee: 21711, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VOLNAY", insee: 21712, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VONGES", insee: 21713, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "VOSNE ROMANEE", insee: 21714, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VOUDENAY", insee: 21715, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VOUGEOT", insee: 21716, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VOULAINES LES TEMPLIERS", insee: 21717, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "TROCHERES", insee: 21644, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "TROUHANS", insee: 21645, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "TROUHAUT", insee: 21646, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "TRUGNY", insee: 21647, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "TURCEY", insee: 21648, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "UNCEY LE FRANC", insee: 21649, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "URCY", insee: 21650, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VAL SUZON", insee: 21651, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VANDENESSE EN AUXOIS", insee: 21652, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VANNAIRE", insee: 21653, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VANVEY", insee: 21655, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VARANGES", insee: 21656, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "VAROIS ET CHAIGNOT", insee: 21657, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "VAUCHIGNON", insee: 21658, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VAUX SAULES", insee: 21659, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VEILLY", insee: 21660, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VELARS SUR OUCHE", insee: 21661, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "VELOGNY", insee: 21662, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VENAREY LES LAUMES", insee: 21663, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VERDONNET", insee: 21664, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VERNOIS LES VESVRES", insee: 21665, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VERNOT", insee: 21666, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VERONNES", insee: 21667, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VERREY SOUS DREE", insee: 21668, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VERREY SOUS SALMAISE", insee: 21670, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VERTAULT", insee: 21671, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VESVRES", insee: 21672, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VEUVEY SUR OUCHE", insee: 21673, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VEUXHAULLES SUR AUBE", insee: 21674, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VIANGES", insee: 21675, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VIC DE CHASSENAY", insee: 21676, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VIC DES PRES", insee: 21677, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VIC SOUS THIL", insee: 21678, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VIELMOULIN", insee: 21679, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VIELVERGE", insee: 21680, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "VIEUX CHATEAU", insee: 21681, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VIEVIGNE", insee: 21682, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VIEVY", insee: 21683, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "VIGNOLES", insee: 21684, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VILLAINES EN DUESMOIS", insee: 21685, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLAINES LES PREVOTES", insee: 21686, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLARGOIX", insee: 21687, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLARS ET VILLENOTTE", insee: 21689, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLARS FONTAINE", insee: 21688, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VILLEBERNY", insee: 21690, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLEBICHOT", insee: 21691, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "VILLECOMTE", insee: 21692, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "VILLEDIEU", insee: 21693, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLEFERRY", insee: 21694, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "VILLEMERVRY", insee: 52530, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST MARIE SUR OUCHE", insee: 21559, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST MARTIN DE LA MER", insee: 21560, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST MARTIN DU MONT", insee: 21561, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST MAURICE SUR VINGEANNE", insee: 21562, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST MESMIN", insee: 21563, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST NICOLAS LES CITEAUX", insee: 21564, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST PHILIBERT", insee: 21565, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST PIERRE EN VAUX", insee: 21566, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST PRIX LES ARNAY", insee: 21567, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST REMY", insee: 21568, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST ROMAIN", insee: 21569, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST SABINE", insee: 21570, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST SAUVEUR", insee: 21571, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST SEINE EN BACHE", insee: 21572, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ST SEINE L'ABBAYE", insee: 21573, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST SEINE SUR VINGEANNE", insee: 21574, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST SYMPHORIEN SUR SAONE", insee: 21575, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ST THIBAULT", insee: 21576, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST USAGE", insee: 21577, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ST VICTOR SUR OUCHE", insee: 21578, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SULLY", insee: 71530, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SUSSEY", insee: 21615, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "TAILLY", insee: 21616, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "TALANT", insee: 21617, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "TALMAY", insee: 21618, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "TANAY", insee: 21619, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "TARSUL", insee: 21620, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "TART L'ABBAYE", insee: 21621, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "TART LE BAS", insee: 21622, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "TART LE HAUT", insee: 21623, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "TELLECEY", insee: 21624, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "TERNANT", insee: 21625, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "TERREFONDREE", insee: 21626, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "THENISSEY", insee: 21627, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "THOIRES", insee: 21628, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "THOISY LA BERCHERE", insee: 21629, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "THOISY LE DESERT", insee: 21630, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "THOMIREY", insee: 21631, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "THOREY EN PLAINE", insee: 21632, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "THOREY SOUS CHARNY", insee: 21633, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "THOREY SUR OUCHE", insee: 21634, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "THOSTE", insee: 21635, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "THURY", insee: 21636, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "TICHEY", insee: 21637, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "TIL CHATEL", insee: 21638, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "TILLENAY", insee: 21639, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "TORCY ET POULIGNY", insee: 21640, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "TOUILLON", insee: 21641, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "TOUTRY", insee: 21642, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "TRECLUN", insee: 21643, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "SAULX LE DUC", insee: 21587, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SAUSSEY", insee: 21588, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SAUSSY", insee: 21589, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SAVIGNY LE SEC", insee: 21590, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SAVIGNY LES BEAUNE", insee: 21591, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "SAVIGNY SOUS MALAIN", insee: 21592, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SAVILLY", insee: 21593, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SAVOISY", insee: 21594, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "SAVOLLES", insee: 21595, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SAVOUGES", insee: 21596, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "SEGROIS", insee: 21597, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "SEIGNY", insee: 21598, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SELONGEY", insee: 21599, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SEMAREY", insee: 21600, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SEMEZANGES", insee: 21601, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "SEMOND", insee: 21602, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "SEMUR EN AUXOIS", insee: 21603, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SENAILLY", insee: 21604, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SENNECEY LES DIJON", insee: 21605, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "SERRIGNY", insee: 21606, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "SEURRE", insee: 21607, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "SINCEY LES ROUVRAY", insee: 21608, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SOIRANS FOUFFRANS", insee: 21609, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "SOISSONS SUR NACEY", insee: 21610, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "SOMBERNON", insee: 21611, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SOUHEY", insee: 21612, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SOUSSEY SUR BRIONNE", insee: 21613, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SPOY", insee: 21614, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST AGNAN", insee: 58226, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST ANDEUX", insee: 21638, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST ANTHOT", insee: 21539, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST APOLLINAIRE", insee: 21540, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
        { name: "ST AUBIN", insee: 21541, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST BERNARD", insee: 21542, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST BROING LES MOINES", insee: 21543, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ST COLOMBE", insee: 21644, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST COLOMBE SUR SEINE", insee: 21645, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ST DIDIER", insee: 21646, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST EUPHRONE", insee: 21647, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST GERMAIN DE MODEON", insee: 21648, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST GERMAIN LE ROCHEUX", insee: 21649, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ST GERMAIN LES SENAILLY", insee: 21550, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST GERMAIN SOURCE DE LA SE", insee: 21551, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST HELIER", insee: 21552, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ST JEAN DE BOEUF", insee: 21653, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ST JEAN DE LOSNE", insee: 21554, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ST JULIEN", insee: 21555, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ST LEGER DE TRIEY", insee: 21556, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ST MARC SUR SEINE", insee: 21557, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ST MARIE LA BLANCHE", insee: 21558, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "POMMARD", insee: 21492, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "PONCEY LES ATHEE", insee: 21493, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "PONCEY SUR L'IGNON", insee: 21494, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PONT", insee: 21495, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "PONT ET MASSENE", insee: 21497, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "PONTAILLER SUR SAONE", insee: 21498, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "POSANGES", insee: 21499, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "POTHIERES", insee: 21499, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "POUILLENAY", insee: 21500, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "POUILLY EN AUXOIS", insee: 21501, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "POUILLY SUR SAONE", insee: 21502, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "POUILLY SUR VINGEANNE", insee: 21503, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PRALON", insee: 21504, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "PRECY SOUS THIL", insee: 21505, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "PREMEAUX PRISSEY", insee: 21506, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "PREMIERES", insee: 21507, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "PRENOIS", insee: 21508, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PRUSLY SUR OURCE", insee: 21510, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "PUITS", insee: 21511, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "PULIGNY MONTRACHET", insee: 21512, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "QUEMIGNY POISOT", insee: 21513, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "QUEMIGNY SUR SEINE", insee: 21514, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "QUETIGNY", insee: 21515, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "QUINCEROT", insee: 21516, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "QUINCEY", insee: 21517, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "QUINCY LE VICOMTE", insee: 21518, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "RECEY SUR OURCE", insee: 21519, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "REMILLY EN MONTAGNE", insee: 21520, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "REMILLY SUR TILLE", insee: 21521, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "RENEVE", insee: 21522, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "REULLE VERGY", insee: 21523, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "RIEL LES EAUX", insee: 21524, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ROCHEFORT", insee: 21526, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ROILLY", insee: 21528, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ROUGEMONT", insee: 21530, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ROUVRAY", insee: 21531, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ROUVRES EN PLAINE", insee: 21532, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ROUVRES SOUS MEILLY", insee: 21533, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "RUFFEY LES BEAUNE", insee: 21534, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "RUFFEY LES ECHIREY", insee: 21536, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "SACQUENAY", insee: 21537, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SAFFRES", insee: 21537, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SALIVES", insee: 21539, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "SALMAISE", insee: 21540, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SAMEREY", insee: 21541, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "SANTENAY", insee: 21542, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "SANTOSSE", insee: 21543, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "SAULIEU", insee: 21544, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "SAULON LA CHAPELLE", insee: 21545, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "SAULON LA RUE", insee: 21546, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "MOREY ST DENIS", insee: 21442, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MOSSON", insee: 21444, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MOUTIERS ST JEAN", insee: 21446, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MUSIGNY", insee: 21447, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MUSSY LA FOSSE", insee: 21448, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MUSSY SUR SEINE", insee: 10261, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "NAN SOUS THIL", insee: 21449, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "NANTOUX", insee: 21450, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "NESLE ET MASSOULT", insee: 21451, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "NEUILLY LES DIJON", insee: 21452, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "NICEY", insee: 21454, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "NOD SUR SEINE", insee: 21455, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "NOGENT LES MONTBARD", insee: 21456, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "NOIDAN", insee: 21457, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "NOIRON SOUS GEVREY", insee: 21458, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "NOIRON SUR BEZE", insee: 21459, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "NOIRON SUR SEINE", insee: 21460, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "NOLAY", insee: 21461, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "NORGES LA VILLE", insee: 21462, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "NORMIER", insee: 21463, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "NUITS ST GEORGES", insee: 21464, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "OBTREE", insee: 21465, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "OIGNY", insee: 21466, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "OISILLY", insee: 21467, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ORAIN", insee: 21468, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ORGEUX", insee: 21469, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ORIGNY", insee: 21470, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ORMOY SUR AUBE", insee: 52368, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ORRET", insee: 21471, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ORVILLE", insee: 21472, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "OUGES", insee: 21473, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "PAGNY LA VILLE", insee: 21474, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "PAGNY LE CHATEAU", insee: 21475, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "PAINBLANC", insee: 21476, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "PANGES", insee: 21477, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PASQUES", insee: 21478, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PELLEREY", insee: 21479, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PERCEY LE GRAND", insee: 70408, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PERNAND VERGELESSES", insee: 21480, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "PERRIGNY LES DIJON", insee: 21481, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "PERRIGNY SUR L'OGNON", insee: 21482, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "PICHANGES", insee: 21483, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "PLANAY", insee: 21484, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "PLOMBIERES LES DIJON", insee: 21485, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "PLUVAULT", insee: 21486, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "PLUVET", insee: 21487, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "POINCON LES LARREY", insee: 21488, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "POISEUL LA GRANGE", insee: 21489, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "POISEUL LA VILLE LAPERRIERE", insee: 21490, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "POISEUL LES SAULX", insee: 21491, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" }
    { name: "LECHATELET", insee: 21344, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LEFFOND", insee: 70300, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "LERY", insee: 21345, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "LES GOULLES", insee: 21303, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LES MAILLYS", insee: 21371, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LEUGLAY", insee: 21346, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LEVERNOIS", insee: 21347, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "LICEY SUR VINGEANNE", insee: 21348, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "LIERNAIS", insee: 21349, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "LIGNEROLLES", insee: 21350, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LOUEILLEY", insee: 70305, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "LONGCHAMP", insee: 21351, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LONGEAULT", insee: 21462, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LONGECOURT EN PLAINE", insee: 21463, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LONGECOURT LES CULETRE", insee: 21354, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "LONGVIC", insee: 21355, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "LOSNE", insee: 21358, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LOUESME", insee: 21367, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LUCENAY LE DUC", insee: 21358, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "LUCEY", insee: 21359, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LUSIGNY SUR OUCHE", insee: 21360, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "LUX", insee: 21361, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MACONGE", insee: 21362, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MAGNIEN", insee: 21363, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MAGNY LA VILLE", insee: 21005, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MAGNY LAMBERT", insee: 21204, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MAGNY LES AUBIGNY", insee: 21265, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "MAGNY LES VILLERS", insee: 21368, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MAGNY MONTARLOT", insee: 21367, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "MAGNY ST MEDARD", insee: 21369, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MAGNY SUR TILLE", insee: 21370, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "MAISEY LE DUC", insee: 21372, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MALAIN", insee: 21373, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "MALIGNY", insee: 21374, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MANLAY", insee: 21375, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MARANDEUIL", insee: 21376, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MARCELLOIS", insee: 21377, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MARCENAY", insee: 21378, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MARCHESEUIL", insee: 21379, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MARCIGNY SOUS THIL", insee: 21380, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MARCILLY LES VITTEAUX", insee: 21381, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MARCILLY OGNY", insee: 21382, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MARCILLY SUR TILLE", insee: 21383, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MAREY LES FUSSEY", insee: 21384, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MAREY SUR TILLE", insee: 21385, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MARIGNY LE CAHOUET", insee: 21386, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MARIGNY LES REULLEE", insee: 21387, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MARLIENS", insee: 21388, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "MARMAGNE", insee: 21389, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MARSANNAY LA COTE", insee: 21390, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "MARSANNAY LE BOIS", insee: 21391, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MARTROIS", insee: 21902, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MASSINGY", insee: 21393, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MASSINGY LES SEMUR", insee: 21904, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MASSINGY LES VITTEAUX", insee: 21395, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MAUVILLY", insee: 21306, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MAVILLY MANDELOT", insee: 21997, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MAXILLY SUR SAONE", insee: 21398, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "MEILLY SUR ROUVRES", insee: 21399, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MELOISEY", insee: 21401, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MENESBLE", insee: 21402, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MENESSAIRE", insee: 21403, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MENETREUX LE PITOIS", insee: 21404, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MERCEUIL", insee: 21405, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MESMONT", insee: 21406, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MESSANGES", insee: 21407, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MESSIGNY ET VANTOUX", insee: 21408, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MEUILLEY", insee: 21409, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MEULSON", insee: 21410, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MEURSANGES", insee: 21411, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MEURSAULT", insee: 21412, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MILLERY", insee: 21413, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MIMEURE", insee: 21414, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MINOT", insee: 21416, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MIREBEAU SUR BEZE", insee: 21416, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" }
    { name: "MISSERY", insee: 21417, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MOITRON", insee: 21418, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MOLESMES", insee: 21419, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MOLINOT", insee: 21420, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MOLOY", insee: 21421, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MOLPHEY", insee: 21422, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MONT ST JEAN", insee: 21423, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MONTAGNY LES BEAUNE", insee: 21424, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MONTAGNY LES SEURRE", insee: 21425, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MONTBARD", insee: 21495, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTBERTHAULT", insee: 21426, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTCEAU ET ECHARNANT", insee: 21427, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MONTHELIE", insee: 21428, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MONTIGNY MONTFORT", insee: 21429, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTIGNY MORNAY VILLENEU", insee: 21453, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MONTIGNY ST BARTHELEMY", insee: 21430, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTIGNY SUR ARMANCON", insee: 21431, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTIGNY SUR AUBE", insee: 21432, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTLAY EN AUXOIS", insee: 21434, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTLIOT ET COURCELLES", insee: 21435, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTHMAIN", insee: 21436, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "MONTMANCON", insee: 21437, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "MONTMOYEN", insee: 21438, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "MONTOILLOT", insee: 21439, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "MONTOT", insee: 21440, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "GRANCEY SUR OURCE", insee: 21305, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "GRENAND LES SOMBERNON", insee: 21306, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "GRESIGNY STE REINE", insee: 21307, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "GRIGNON", insee: 21308, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "GRISELLES", insee: 21309, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "GROSBOIS EN MONTAGNE", insee: 21310, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "GROSBOIS LES TICHEY", insee: 21311, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "GURGY LA VILLE", insee: 21312, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "GURGY LE CHATEAU", insee: 21313, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "HAUTEROCHE", insee: 21314, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "HAUTEVILLE LES DIJON", insee: 21315, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "HEUILLEY SUR SAONE", insee: 21316, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "IS SUR TILLE", insee: 21317, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "IVRY EN MONTAGNE", insee: 21318, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "IZEURE", insee: 21319, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "IZIER", insee: 21320, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "JAILLY LES MOULINS", insee: 21321, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "JALLANGES", insee: 21322, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "JANCIGNY", insee: 21323, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "JEUX LES BARD", insee: 21324, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "JOUEY", insee: 21325, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "JOURS EN VAUX", insee: 21327, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "JOURS LES BAIGNEUX", insee: 21326, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "JUILLENAY", insee: 21328, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "JUILLY", insee: 21329, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "L'ETANG VERGY", insee: 21254, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "LA BUSSIERE SUR OUCHE", insee: 21250, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "LA CHAUME", insee: 21169, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LA MOTTE TERNANT", insee: 21445, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "LA ROCHE EN BRENIL", insee: 21526, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "LA ROCHE VANNEAU", insee: 21528, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "LA ROCHEPOT", insee: 21527, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "LA VILLENEUVE LES CONVERS", insee: 21695, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "LABERGEMENT FOIGNEY", insee: 21330, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LABERGEMENT LES AUXONNE", insee: 21331, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LABERGEMENT LES SEURRE", insee: 21332, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "LABRUYERE", insee: 21333, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LACANCHE", insee: 21334, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "LACOUR D'ARCENAY", insee: 21335, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "LAIGNES", insee: 21336, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LAMARCHE SUR SAONE", insee: 21337, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LAMARGELLE", insee: 21338, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "LANTENAY", insee: 21339, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "LANTHES", insee: 21340, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "LANTILLY", insee: 21341, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "LANTY SUR AUBE", insee: 52272, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "LAPERRIERE SUR SAONE", insee: 21342, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "LARREY", insee: 21343, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" }
    { name: "LE FETE", insee: 21264, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "LE MEIX", insee: 21400, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ETAIS", insee: 21262, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ETALANTE", insee: 21253, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ETAULES", insee: 21255, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ETEVAUX", insee: 21256, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ETORMAY", insee: 21267, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ETROCHEY", insee: 21258, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "FAIN LES MONTBARD", insee: 21258, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FAIN LES MOUTIERS", insee: 21260, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FAUVERNEY", insee: 21261, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "FAVEROLLES LES LUCEY", insee: 21262, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "FENAY", insee: 21263, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "FIXIN", insee: 21265, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "FLACEY", insee: 21268, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "FLAGEY LES AUXONNE", insee: 21268, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "FLAGEY LES ECHEZEAUX", insee: 21267, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "FLAMMERANS", insee: 21268, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "FLAVIGNEROT", insee: 21270, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "FLAVIGNY SUR OZERAIN", insee: 21274, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FLEE", insee: 21272, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FLEUREY SUR OUCHE", insee: 21273, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "FOISSY", insee: 21274, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "FONCEGRIVE", insee: 21276, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "FONTAINE FRANCAISE", insee: 21277, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "FONTAINE LES DIJON", insee: 21276, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "FONTAINES EN DUESMOIS", insee: 21276, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FONTAINES LES SECHES", insee: 21279, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "FONTANGY", insee: 21280, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FONTENELLE", insee: 21281, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "FORLEANS", insee: 21282, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FRAIGNOT ET VESVROTTE", insee: 21283, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "FRANCHEVILLE", insee: 21284, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "FRANXAULT", insee: 21286, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "FRENOIS", insee: 21286, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "FRESNES", insee: 21287, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FROLOIS", insee: 21286, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "FUSSEY", insee: 21289, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "GEMEAUX", insee: 21290, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "GENAY", insee: 21291, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "GENLIS", insee: 21292, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "GERGUEIL", insee: 21293, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "GERLAND", insee: 21294, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "GEVREY CHAMBERTIN", insee: 21295, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "GEVROLLES", insee: 21296, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "GILLY LES CITEAUX", insee: 21297, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "GISSEY LE VIEL", insee: 21298, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "GISSEY SOUS FLAVIGNY", insee: 21299, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "GISSEY SUR OUCHE", insee: 21300, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "GLANON", insee: 21301, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "GOMMEVILLE", insee: 21302, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "GRANCEY LE CHATEAU NEUVELY", insee: 21304, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" }
    { name: "COURBAN", insee: 21202, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "COURCELLES FREMOY", insee: 21203, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "COURCELLES LES MONTBARD", insee: 21204, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "COURCELLES LES SEMUR", insee: 21205, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "COURLON", insee: 21207, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "COURTIVRON", insee: 21208, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "COUTERNON", insee: 21209, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "CREANCEY", insee: 21210, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CRECEY SUR TILLE", insee: 21211, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CREPAND", insee: 21212, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CRIMOLOIS", insee: 21213, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "CRUGEY", insee: 21214, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CUISEREY", insee: 21215, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CULETRE", insee: 21216, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CURLEY", insee: 21217, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CURTIL ST SEINE", insee: 21218, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CURTIL VERGY", insee: 21219, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CUSSEY LES FORGES", insee: 21220, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CUSSY LA COLONNE", insee: 21221, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CUSSY LE CHATEL", insee: 21222, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "DAIX", insee: 21223, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "DAMPIERRE EN MONTAGNE", insee: 21224, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "DAMPIERRE ET FLEE", insee: 21225, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "DARCEY", insee: 21206, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "DAROIS", insee: 21227, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "DETAIN ET BRUANT", insee: 21228, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "DIANCEY", insee: 21229, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "DIENAY", insee: 21230, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "DIJON", insee: 21231, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "DOMPIERRE EN MORVAN", insee: 21232, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "DRAMBON", insee: 21233, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "DREE", insee: 21234, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "DUESME", insee: 21235, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "EBATY", insee: 21236, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ECHALOT", insee: 21287, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ECHANNAY", insee: 21238, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ECHENON", insee: 21239, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ECHEVANNES", insee: 21240, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ECHEVRONNE", insee: 21241, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ECHIGEY", insee: 21242, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ECUTIGNY", insee: 21243, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "EGUILLY", insee: 21244, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "EPAGNY", insee: 21245, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "EPERNAY SOUS GEVREY", insee: 21246, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "EPINAC", insee: 71190, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "EPOISSES", insee: 21247, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ERINGES", insee: 21248, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ESBARRES", insee: 21249, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ESSAROIS", insee: 21250, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ESSEY", insee: 21251, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" }
    { name: "CHARREY SUR SEINE", insee: 21149, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHASSAGNE MONTRACHET", insee: 21150, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHASSEY", insee: 21151, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHATEAUNEUF", insee: 21152, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHATELLENOT", insee: 21153, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHATILLON SUR SEINE", insee: 21154, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAUDENAY LA VILLE", insee: 21165, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAUDENAY LE CHATEAU", insee: 21166, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAUGEY", insee: 21167, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAUME ET COURCHAMP", insee: 21168, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CHAUME LES BAIGNEUX", insee: 21169, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAUMONT LE BOIS", insee: 21161, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAUX", insee: 21162, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAZEUIL", insee: 21163, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAZILLY", insee: 21164, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHEMIN D'AISEY", insee: 21165, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHENOVE", insee: 21166, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "CHEUGE", insee: 21167, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CHEVANNAY", insee: 21168, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHEVANNES", insee: 21169, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHEVIGNY EN VALLIERES", insee: 21170, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHEVIGNY ST SAUVEUR", insee: 21171, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "CHIVRES", insee: 21172, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHOREY", insee: 21173, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CIREY LES PONTAILLER", insee: 21175, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "CIVRY EN MONTAGNE", insee: 21176, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CLAMEREY", insee: 21177, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CLEMENCEY", insee: 21178, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CLENAY", insee: 21179, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CLOMOT", insee: 21181, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "COLLONGES LES BEVY", insee: 21182, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "COLLONGES LES PREMIERES", insee: 21183, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "COLOMBIER", insee: 21184, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "COMBERTAULT", insee: 21185, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "COMBLANCHIEN", insee: 21186, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "COMMARIN", insee: 21187, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORBERON", insee: 21188, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORCELLES LES ARTS", insee: 21190, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORCELLES LES CITEAUX", insee: 21191, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORCELLES LES MONTS", insee: 21192, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "CORGENGOUX", insee: 21193, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORGOLOIN", insee: 21194, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORMOT LE GRAND", insee: 21195, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORPEAU", insee: 21196, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CORPOYER LA CHAPELLE", insee: 21197, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CORROMBLES", insee: 21198, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CORSAINT", insee: 21199, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "COUBLANC", insee: 52145, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "COUCHEY", insee: 21200, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "COULMIER LE SEC", insee: 21201, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BOUX SOUS SALMAISE", insee: 21098, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BOUZE LES BEAUNE", insee: 21099, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BRAIN", insee: 21100, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BRAUX", insee: 21101, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BRAZEY EN MORVAN", insee: 21102, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BRAZEY EN PLAINE", insee: 21103, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BREMUR ET VAUROIS", insee: 21104, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BRESSEY SUR TILLE", insee: 21105, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BRETENIERES", insee: 21106, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BRETIGNY", insee: 21107, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BRIANNY", insee: 21108, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BRION SUR OURCE", insee: 21109, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BROCHON", insee: 21110, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BROGNON", insee: 21111, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BROIN", insee: 21112, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BROINDON", insee: 21113, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BUFFON", insee: 21114, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BUNCEY", insee: 21115, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BURE LES TEMPLIERS", insee: 21116, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BUSSEAUT", insee: 21117, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BUSSEROTTE ET MONTENAIL", insee: 21118, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BUSSIERES", insee: 21119, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BUSSY LA PESLE", insee: 21120, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BUSSY LE GRAND", insee: 21122, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BUXEROLLES", insee: 21123, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" }
    { name: "CENSEREY", insee: 21124, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CERILLY", insee: 21125, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CESSEY SUR TILLE", insee: 21126, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "CHAIGNAY", insee: 21127, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CHAILLY SUR ARMANCON", insee: 21128, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAMBAIN", insee: 21129, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAMBEIRE", insee: 21130, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "CHAMBLANC", insee: 21131, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAMBOEUF", insee: 21132, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAMBOLLE MUSIGNY", insee: 21133, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAMESSON", insee: 21134, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAMP D'OISEAU", insee: 21137, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAMPAGNE SUR VINGEANNE", insee: 21135, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CHAMPAGNY", insee: 21136, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CHAMPDOTRE", insee: 21138, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "CHAMPEAU", insee: 21139, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHAMPIGNOLLES", insee: 21140, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "CHAMPRENAULT", insee: 21141, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHANCEAUX", insee: 21142, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CHANNAY", insee: 21143, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "CHARENCEY", insee: 21144, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHARIGNY", insee: 21145, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHARMES", insee: 21146, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "CHARNY", insee: 21147, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "CHARREY SUR SAONE", insee: 21148, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BARJON", insee: 21049, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BAUBIGNY", insee: 21050, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BAULME LA ROCHE", insee: 21051, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BEAULIEU", insee: 21052, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BEAUMONT SUR VINGEANNE", insee: 21053, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BEAUNE", insee: 21054, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BEAUNOTTE", insee: 21055, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BEIRE LE CHATEL", insee: 21056, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BEIRE LE FORT", insee: 21057, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BELAN SUR OURCE", insee: 21058, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BELLEFOND", insee: 21059, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "BELLENEUVE", insee: 21060, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BELLENOD SUR SEINE", insee: 21061, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BELLENOT SOUS POUILLY", insee: 21062, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BENEUVRE", insee: 21063, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BENOISEY", insee: 21064, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BESSEY EN CHAUME", insee: 21065, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BESSEY LA COUR", insee: 21066, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BESSEY LES CITEAUX", insee: 21067, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BEUREY BAUGUAY", insee: 21068, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BEURIZOT", insee: 21069, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BEVY", insee: 21070, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BEZE", insee: 21071, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BEZOUOTTE", insee: 21072, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BIERRE LES SEMUR", insee: 21073, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BIERRY LES BELLES FONTAINES", insee: 89042, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
        { name: "BILLEY", insee: 21074, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BILLY LES CHANCEAUX", insee: 21075, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BINGES", insee: 21076, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BISSEY LA COTE", insee: 21077, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BISSEY LA PIERRE", insee: 21078, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BLAGNY SUR VINGEANNE", insee: 21079, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BLAISY BAS", insee: 21080, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BLAISY HAUT", insee: 21081, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BLANCEY", insee: 21082, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BLANOT", insee: 21083, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BLESSEY", insee: 21084, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BLIGNY LE SEC", insee: 21085, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BLIGNY LES BEAUNE", insee: 21086, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BLIGNY SUR OUCHE", insee: 21087, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BONCOURT LE BOIS", insee: 21088, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BONNENCONTRE", insee: 21089, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "BOUDREVILLE", insee: 21090, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BOUHEY", insee: 21091, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BOUILLAND", insee: 21092, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BOUIX", insee: 21093, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BOURBERAIN", insee: 21094, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BOUSSELANGE", insee: 21095, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BOUSSENOIS", insee: 21096, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BOUSSEY", insee: 21097, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "AGENCOURT", insee: 21001, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "AGEY", insee: 21002, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "AHUY", insee: 21003, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "AIGNAY LE DUC", insee: 21004, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "AISEREY", insee: 21005, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "AISEY SUR SEINE", insee: 21006, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "AISY SOUS THIL", insee: 21007, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "AISY SUR ARMANCON", insee: 89004, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ALISE STE REINE", insee: 21008, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ALLEREY", insee: 21009, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ALLIGNY EN MORVAN", insee: 58003, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ALOXE CORTON", insee: 21010, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "AMPILLY LE SEC", insee: 21012, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "AMPILLY LES BORDES", insee: 21011, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ANCEY", insee: 21013, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ANTHEUIL", insee: 21014, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ANTIGNY LA VILLE", insee: 21015, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ARC SUR TILLE", insee: 21021, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ARCEAU", insee: 21016, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "ARCENANT", insee: 21017, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ARCEY", insee: 21018, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ARCONCEY", insee: 21020, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ARGILLY", insee: 21022, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "ARNAY LE DUC", insee: 21023, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "ARNAY SOUS VITTEAUX", insee: 21024, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ARRANS", insee: 21025, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "ARTHONNAY", insee: 89019, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ASNIERES EN MONTAGNE", insee: 21026, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "ASNIERES LES DIJON", insee: 21027, bo: "DIJON", base: "DIJON", region: "Bourgogne" },
    { name: "ATHEE", insee: 21028, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "ATHIE", insee: 21029, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "AUBAINE", insee: 21030, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "AUBIGNY EN PLAINE", insee: 21031, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "AUBIGNY LA RONCE", insee: 21032, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "AUBIGNY LES SOMBERNON", insee: 21033, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "AUTRICOURT", insee: 21034, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "AUVILLARS SUR SAONE", insee: 21035, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "AUXANT", insee: 21036, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "AUXEY DURESSES", insee: 21037, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "AUXONNE", insee: 21038, bo: "GENLIS", base: "DIJON", region: "Bourgogne" },
    { name: "AVELANGES", insee: 21039, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "AVOSNES", insee: 21040, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "AVOT", insee: 21041, bo: "IS/TILLE", base: "DIJON", region: "Bourgogne" },
    { name: "BAGNOT", insee: 21042, bo: "BEAUNE", base: "BEAUNE", region: "Bourgogne" },
    { name: "BAIGNEUX LES JUIFS", insee: 21043, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BALOT", insee: 21044, bo: "CHATILLON", base: "SEMUR", region: "Bourgogne" },
    { name: "BARBIREY SUR OUCHE", insee: 21045, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BARD LE REGULIER", insee: 21046, bo: "ARNAY", base: "BEAUNE", region: "Bourgogne" },
    { name: "BARD LES EPOISSES", insee: 21047, bo: "SEMUR", base: "SEMUR", region: "Bourgogne" },
    { name: "BARGES", insee: 21048, bo: "GENLIS", base: "DIJON", region: "Bourgogne" }

    // Ajoute toutes les autres communes ici avec leurs coordonnées GPS
];

// Fonction pour gérer la recherche et l'affichage des résultats
document.getElementById('commune-input').addEventListener('input', function () {
    const input = this.value.toLowerCase();
    const suggestionsDiv = document.getElementById('suggestions');
    suggestionsDiv.innerHTML = ''; // Clear previous suggestions

    if (input) {
        const filteredCommunes = communes.filter(c => c.name.toLowerCase().startsWith(input));
        filteredCommunes.forEach(commune => {
            const div = document.createElement('div');
            div.textContent = commune.name;
            div.onclick = function () {
                selectCommune(commune);
            };
            suggestionsDiv.appendChild(div);
        });
    }
});

function selectCommune(commune) {
    document.getElementById('commune-input').value = commune.name;
    document.getElementById('insee-code').textContent = commune.insee;
    document.getElementById('bo-output').textContent = commune.bo;
    document.getElementById('base-output').textContent = commune.base;

    // Clear suggestions
    document.getElementById('suggestions').innerHTML = '';

    // Update map with the location
    updateMap(commune.lat, commune.lon);
}

// Fonction pour mettre à jour la carte
function updateMap(lat, lon) {
    const map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: { lat: lat, lng: lon },
    });

    // Add a marker at the selected commune's location
    new google.maps.Marker({
        position: { lat: lat, lng: lon },
        map: map,
    });
}
